spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.129/sellbak?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.0.129
    port: 6379
server:
  context-path: /sell
  port: 8080
wechat:
  mpAppId: wxb962cbf908779e5e
  mpAppScret: 01d65e5f44d6e2d777996dc60e94ea58
  openAppId: 123455
  openAppScret: 123124
  mchId: 1234123124
  mchKey: 12341241241
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://merryyou.cn/sell/pay/notify

projectUrl:
  wechatMpAuthorize: http://merryyou.s1.natapp.cc/
  wechatOpenAuthorize: http://merryyou.s1.natapp.cc/
  sell: http://merryyou.s1.natapp.cc/

#mybatis:
#  mapper-locations:


#apache ab
#ab -n 100 -c 100 http://www.baidu.com    -n 100 请求  -c 100 人  -c 60秒
#ab -t 60 -c 100 http://www.baidu.com  60秒内100个人请求
